-- Places, and where their figures came from.
--
-- data_source is not bookkeeping. Every baseline this product shows carries a provenance string
-- back to one of these rows, because the difference between a government statistic and somebody's
-- research is the difference between advice and noise, and the user is entitled to know which one
-- they are looking at.

CREATE TABLE country (
    code                 TEXT PRIMARY KEY,
    name                 TEXT         NOT NULL,
    currency             TEXT         NOT NULL,
    -- The one column that makes staleness behave differently per country. Drift is
    -- annual_inflation_pct * age_months / 12, so the United States at 3% keeps a figure fresh for
    -- twenty months while Lebanon at 17.3% is stale inside eleven. Same code, one column.
    annual_inflation_pct NUMERIC(6, 2) NOT NULL CHECK (annual_inflation_pct >= 0),
    inflation_as_of      DATE         NOT NULL,
    -- Shown to the user, not kept for developers: Lebanon being dollar-priced in practice is
    -- something a person needs to know before they trust a figure in dollars.
    data_note            TEXT         NOT NULL DEFAULT '',
    -- A country with no data must never appear in the dropdown. Choosing it is a dead end the user
    -- cannot tell apart from their own mistake.
    listed               BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE data_source (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    url          TEXT,
    retrieved_at DATE NOT NULL,
    license_note TEXT NOT NULL
);

CREATE TABLE metro_area (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code    TEXT    NOT NULL REFERENCES country (code),
    -- The only lookup key there is. A city name a user types is display text and never resolves to
    -- one of these, which is what removes geocoding and fuzzy matching from the product: a typo
    -- can never almost-match the wrong metro.
    slug            TEXT    NOT NULL UNIQUE,
    display_name    TEXT    NOT NULL,
    admin1          TEXT,
    -- Left empty by the curated seed. It exists for a future source that identifies metros by an
    -- external geography id, so adding one is not a migration.
    external_geo_id TEXT,
    population      INTEGER,
    sort_rank       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX metro_area_by_country ON metro_area (country_code, sort_rank);
