-- The read path: what a category costs, per city and per country.
--
-- Materialised rather than computed per request. The curated Lebanese figures are absolute amounts
-- with no index to multiply by, while a future derived source multiplies a national figure by a
-- regional price parity. Computing at read time would grow a branch per country on the hot path;
-- one table means one query and one adapter, and the derivation column keeps the audit trail.

CREATE TABLE national_baseline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code    TEXT          NOT NULL REFERENCES country (code),
    category        TEXT          NOT NULL,
    -- NULLABLE, and load-bearing. Curated figures are not split by income; a future BLS-derived
    -- source is. Folding this column into a primary key - the obvious thing to do - would make
    -- NULL impossible and turn reviving that pipeline into a migration plus a backfill instead of
    -- a new class. Hence a surrogate key and the two partial unique indexes below.
    income_quintile TEXT,
    monthly_amount  NUMERIC(14, 2) NOT NULL CHECK (monthly_amount >= 0),
    confidence      TEXT          NOT NULL,
    source_id       TEXT          NOT NULL REFERENCES data_source (id),
    as_of           DATE          NOT NULL,
    -- How far a user-submitted figure may sit from this estimate and stay believable, as a
    -- percentage of it. Stored beside the figure it qualifies because a band is a multiple of an
    -- estimate and is meaningless apart from it. Per category on purpose: rent inside one country
    -- spans Wichita to San Francisco, a single person's grocery bill does not, and one tolerance
    -- cannot be right for both.
    low_pct         INTEGER       NOT NULL CHECK (low_pct >= 0),
    high_pct        INTEGER       NOT NULL CHECK (high_pct > low_pct)
);

CREATE UNIQUE INDEX national_baseline_one_per_quintile
    ON national_baseline (country_code, category, income_quintile)
    WHERE income_quintile IS NOT NULL;

CREATE UNIQUE INDEX national_baseline_one_without_quintile
    ON national_baseline (country_code, category)
    WHERE income_quintile IS NULL;

CREATE TABLE city_category_baseline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metro_id        BIGINT        NOT NULL REFERENCES metro_area (id),
    category        TEXT          NOT NULL,
    -- Nullable for the same reason as above, and for the same one column's worth of future.
    income_quintile TEXT,
    monthly_amount  NUMERIC(14, 2) NOT NULL CHECK (monthly_amount >= 0),
    -- A city row can only ever be one of these three. USER_PROVIDED belongs to one person and
    -- lives in user_category_override; ESTIMATED is a country-level fallback and lives in
    -- national_baseline. Without this constraint the resolver's layers could be bypassed by a bad
    -- row, and a guess would end up wearing whichever badge somebody typed.
    confidence      TEXT          NOT NULL
        CHECK (confidence IN ('OFFICIAL', 'CONTRIBUTED', 'CROWDSOURCED')),
    source_id       TEXT          NOT NULL REFERENCES data_source (id),
    as_of           DATE          NOT NULL,
    -- The audit trail for a derived figure, e.g. "CEX(HOUSING,q3) 1842.00 x RPP_RENTS 178.2/100".
    -- Empty on curated rows, which were researched rather than computed.
    derivation      TEXT
);

CREATE UNIQUE INDEX city_category_baseline_one_per_quintile
    ON city_category_baseline (metro_id, category, income_quintile, confidence)
    WHERE income_quintile IS NOT NULL;

CREATE UNIQUE INDEX city_category_baseline_one_without_quintile
    ON city_category_baseline (metro_id, category, confidence)
    WHERE income_quintile IS NULL;

CREATE INDEX city_category_baseline_by_metro ON city_category_baseline (metro_id, category);
