-- The user layer. Everything here belongs to exactly one person until they say otherwise.
--
-- A user's own figure beats every other source permanently, including official statistics, because
-- they are the only source with access to their actual receipts. Sharing it is a separate, later,
-- opt-in step that goes through city_contribution and is published by nothing except approval.

CREATE TABLE user_category_override (
    user_id        TEXT          NOT NULL,
    category       TEXT          NOT NULL,
    monthly_amount NUMERIC(14, 2) NOT NULL CHECK (monthly_amount >= 0),
    set_at         DATE          NOT NULL,
    -- Whether the user's own transactions agree with what they typed. Recorded, never enforced:
    -- a rent paid in cash leaves no trace, and overruling somebody about their own rent is not a
    -- trade this product makes.
    corroboration  TEXT          NOT NULL,
    PRIMARY KEY (user_id, category)
);

CREATE TABLE user_manual_location (
    user_id      TEXT PRIMARY KEY,
    country_code TEXT NOT NULL REFERENCES country (code),
    -- DISPLAY ONLY. Deliberately not a foreign key and deliberately not indexed for lookup: the
    -- moment anything resolves a metro from this column, a misspelling can silently select the
    -- wrong city's cost of living and every number downstream is wrong with nothing crashing.
    city_label   TEXT NOT NULL
);

CREATE TABLE city_contribution (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Set when the author picked a listed city, null when they typed their own.
    metro_id         BIGINT        REFERENCES metro_area (id),
    -- Kept so a human triaging the queue can read what the author meant. Still never a lookup key.
    city_label       TEXT,
    country_code     TEXT          NOT NULL REFERENCES country (code),
    user_id          TEXT          NOT NULL,
    category         TEXT          NOT NULL,
    monthly_amount   NUMERIC(14, 2) NOT NULL CHECK (monthly_amount >= 0),
    submitted_at     DATE          NOT NULL,
    validation_state TEXT          NOT NULL
        CHECK (validation_state IN ('CANDIDATE', 'REJECTED', 'QUEUED', 'PUBLISHED')),
    corroboration    TEXT          NOT NULL,
    -- Why it was rejected, in words the author could be shown. A rejection with no explanation
    -- reads as the app calling them a liar.
    validation_notes TEXT          NOT NULL DEFAULT '',
    CONSTRAINT city_contribution_names_a_place CHECK (metro_id IS NOT NULL OR city_label IS NOT NULL)
);

CREATE INDEX city_contribution_by_state ON city_contribution (validation_state, submitted_at);
CREATE INDEX city_contribution_by_author ON city_contribution (user_id);
